name: ActiveLearner
description: Launches Active Learning workflow
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 2.0
date: "2022-02-08"

runtimes:
  - editor: PBJ Workbench
    kernel: Python 3.9
    edition: Standard

tasks:
  - type: create_job
    name: Install dependencies
    entity_label: install_deps
    script: cml/install_deps.py
    arguments: None
    cpu: 4
    memory: 6
    short_summary: Job to install dependencies and download training data.
    environment:
      TASK_TYPE: CREATE/RUN_JOB

  - type: run_job
    entity_label: install_deps
    short_summary: Running install dependencies training job.
    long_summary: >-
      Running the job to install dependencies.
      
  - type: start_application
    short_summary: Create a web application that serves the Active Learner workflow
    long_summary: Create a web application that serves the Active Learner workflow. Note that this prototype requires a minimum of 2 CPUs and 6GB memory.
    name: Active Learner 
    subdomain: al
    description: Create a web application for active learning workflow. Note that this prototype requires a minimum of 2 CPUs and 6GB memory.
    script: apps/app.py
    cpu: 4
    memory: 6
    environment_variables:
      TASK_TYPE: START_APPLICATION
